version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      ELASTIC_HOST: "${ELASTIC_HOST-http://elasticsearch:9200}"
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    build:
      context: extensions/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/config/filebeat.yml
    environment:
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      ELASTIC_HOST: "${ELASTIC_HOST-http://elasticsearch:9200}"
    volumes:
      - ./extensions/filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml:ro,z
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  kibana_config:
    file: ./kibana/config/kibana.yml
  filebeat_config:
    file: ./extensions/filebeat/config/filebeat.yml

networks:
  default:
    external:
      name: external-network