version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - default

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    environment:
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      ELASTIC_HOST: "${ELASTIC_HOST-http://elasticsearch:9200}"
    networks:
      - default
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: extensions/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ELASTIC_USERNAME: "${ELASTIC_USERNAME-elastic}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD-changeme}"
      ELASTIC_HOST: "${ELASTIC_HOST-http://elasticsearch:9200}"
    volumes:
      - ./extensions/filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml:ro,z
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    depends_on:
      - elasticsearch

networks:
  default:
    external:
      name: external-network

volumes:
  elasticsearch:
